(* let create_courses_table = *)
(*   [%rapper *)
(*     execute *)
(*       {sql| *)
(*     CREATE TABLE COURSES ( *)
(*         course_id UUID PRIMARY KEY, *)
(*         instructor VARCHAR NOT NULL, *)
(*         course_url VARCHAR NOT NULL, *)
(*     ) *)
(*     |sql}] *)
(* ;; *)
(**)
(* let migrations = [ "create courses table", create_courses_table ] *)
(**)
(* let () = *)
(*   match Lwt_main.run (Db.Migration.execute migrations) with *)
(*   | Ok () -> print_endline "Migration complete" *)
(*   | Error err -> failwith err *)
(* ;; *)
